name: Unit test

inputs:
  goVersion:
    description: 'Golang version'
    default: 1.19.2
    required: false

runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v2
    with:
      go-version: ${{ inputs.goVersion }}
  - name: Setup Golang caches
    uses: actions/cache@v3
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-golang-
  - name: Check out code into the Go module directory
    uses: actions/checkout@v2
  - name: Run tests
    run: make unit-test