# permissions for end users to view valhallas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valhalla-viewer-role
rules:
- apiGroups:
  - valhalla.itayankri
  resources:
  - valhallas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valhalla.itayankri
  resources:
  - valhallas/status
  verbs:
  - get
