# permissions for end users to edit valhallas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valhalla-editor-role
rules:
- apiGroups:
  - valhalla.itayankri
  resources:
  - valhallas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - valhalla.itayankri
  resources:
  - valhallas/status
  verbs:
  - get
