name: Test | Build | Publish

on:
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: 1.19.2
  K8S_VERSION: v1.24.1

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests
      run: make unit-test
